---
layout: cv
title: "About Me"
subtitle: "Travis Hineman Portfolio"
# use quarto markdown to 
---

<style>
h2, h3, h4 {
    text-align: center;
}
</style>

# Resume

[Download Full Resume](Resume-12-29-23.pdf)


## **Travis Hineman**
#### +1 571-442-7090 | travishineman85@gmail.com | [LinkedIn](http://www.linkedin.com/in/travis-hineman)
---

#### **Education**
##### Bachelor of Business in Business Analytics | *Brigham Young University -Idaho* | Rexburg, ID
2019 - Present

#### **Work Experience**
##### Amazon DSP Delivery Driver | *Metropolitan logistics* | Sterling, VA August 2022 - December 2022
* Developed good customer service skills through delivering up to 600 packages to customer instructions
* Displayed an ability to work and efficiently manage time for up to 10 hours
* Enhanced physical fitness through ability to lift packages weighing up to 50 lbs all day
* Refined attention to detail by demonstrating highest level of integrity, compliance, and adherence within
delivery/transportation services
* Honed strong verbal communication skills while working with a team of 15

##### Delivery Technician | *Mountain Hot Tub* | Helena, MT September 2021 - December 2021
* Delivered and installed up to 3 hot tubs by working in teams including filling and connecting
* Troubleshot onsite problems, offering immediate and long-term solutions

##### Customer Care and Loyalty Agent | *SafeStreetsUSA* | Rexburg, ID March 2021 - June 2021
* Resolved calls from national customers while balancing company policies

##### Service Volunteer | *Church of Jesus Christ of Latter Day Saints* | Tijuana, Baja California
August 2017 - August 2019


#### **Skills**
* Data Analysis: Excel, Power BI, Python, R
* Database Management: MySQL
* Other Technical: QuickBooks, Git/GitHub
* Soft Skills: Customer Service, Communication, Problem-Solving


#### **Languages**
* Spanish - Intermediate


#### **Certifications And Licenses**
* CompTIA A+


#### **Extra Curricular Activities**
* Data Science Society:
* Finance Society:
* Eagle Scout & Boy Scouts of America



<!-- ### Footer

Last updated: May 2024 -->